version: "3.8"
services:
  api:
    build:
      context: ./backend
    environment:
      PORT: 3000
      SALT: "$$2b$$10$$M6XTJ8gP1hDp7j7eGQ5VZu"
      JWT_ACCESS_TOKEN_SECRET_KEY: secret
      JWT_REFRESH_TOKEN_SECRET_KEY: secret2
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: ""
      DB_USERNAME: root
      DB_PASSWORD: password
      ALLOWED_ORIGIN: "${ALLOWED_ORIGIN}"
    ports:
      - "${API_PORT}:${API_PORT}"
    links:
      - db
    depends_on:
      - db

  web:
    build: 
      context: ./frontend
      args: 
        - api_port=${API_PORT}
    ports:
      - "${WEB_PORT}:80"
      
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
