version: "3.8"
services:
  frontapp:
    build: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT = 3000
      - SALT = $2b$10$M6XTJ8gP1hDp7j7eGQ5VZu
      - JWT_ACCESS_TOKEN_SECRET_KEY = secret
      - JWT_REFRESH_TOKEN_SECRET_KEY = secret2
      - DB_HOST = localhost
      - DB_PORT = 27017
      - DB_NAME = 
      - DB_USERNAME = root
      - DB_PASSWORD = password

  api:
    build: ./frontend/Dockerfile
    ports:
      - "3001:3001"
  db:
    image: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
